set(sources
    src/state/State.cpp
    src/state/ui/UiState.cpp
    src/state/gs/GSMainMenu.cpp
    src/state/ui/UISMainMenu.cpp
    src/state/gs/GSDuelHotSeat.cpp
    src/state/ui/UISDuelHotSeat.cpp
    src/Application.cpp
)

set(exe_sources
        src/main.cpp
        ${sources}
)

set(headers
    include/IRenderer.hpp
    include/Renderer.hpp
    include/GUI/IDesktop.hpp
    include/GUI/Desktop.hpp
    include/state/State.hpp
    include/state/AppStateDefs.hpp
    include/state/ILogicState.hpp
    include/state/gs/IGameState.hpp
    include/state/gs/GameState.hpp
    include/state/gs/GSMainMenu.hpp
    include/state/gs/GSDuelHotSeat.hpp
    include/state/gs/GSFinal.hpp
    include/state/ui/IUiState.hpp
    include/state/ui/UiState.hpp
    include/state/ui/UISMainMenu.hpp
    include/state/ui/UISFinal.hpp
    include/state/ui/UISDuelHotSeat.hpp
    include/IApplication.hpp
    include/Application.hpp
)

set(test_sources
  src/ApplicationTests.cpp
)
