if(${PROJECT_NAME}_ENABLE_VCPKG)
  set(VCPKG_FEATURE_FLAGS "versions")

  if(${PROJECT_NAME}_VERBOSE_OUTPUT)
    set(VCPKG_VERBOSE ON)
  endif()
  set(CMAKE_TOOLCHAIN_FILE "${CMAKE_TOOLCHAIN_FILE}" "${CMAKE_BINARY_DIR}/vcpkg.cmake")
endif()
